language: python
python:
  - 3.8

install:
  - pip install -r requirements.txt

script:
  - pytest
  - pylint library_app
  - coverage run -m unittest discover
  - coverage report

after_success:
  - coveralls
